apiVersion: apps/v1
kind: Deployment
metadata:
  name:  myapp
  namespace: development
  labels:
    app:  myapp
spec:
  selector:
    matchLabels:
      app: myapp
  replicas: 1
  template:
    metadata:
      labels:
        app:  myapp
    spec:
      containers:
      - name:  myapp
        image:  nginx:latest
        ports:
        - containerPort: 80